# Generated by Django 5.2.4 on 2025-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours_maths", "0002_reponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecon",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lecons_images/"),
        ),
    ]
