# Generated by Django 5.2.4 on 2025-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours_maths", "0003_lecon_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecon",
            name="image",
        ),
        migrations.AddField(
            model_name="correction",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, upload_to="corrections_pdfs/"
            ),
        ),
        migrations.AddField(
            model_name="exercice",
            name="fichier",
            field=models.FileField(blank=True, null=True, upload_to="exercices_pdfs/"),
        ),
        migrations.AddField(
            model_name="lecon",
            name="fichier",
            field=models.FileField(blank=True, null=True, upload_to="lecons_pdfs/"),
        ),
    ]
