# Generated by Django 5.2.4 on 2025-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours_maths", "0004_remove_lecon_image_correction_fichier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="questions_images/"
            ),
        ),
    ]
