# Generated by Django 5.2.4 on 2025-07-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours_maths", "0005_question_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Explication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="explications_images/"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explication",
                        to="cours_maths.question",
                    ),
                ),
            ],
        ),
    ]
