# Generated by Django 5.2.4 on 2025-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours_maths", "0006_explication"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="titre",
            field=models.CharField(default="Correction sans titre", max_length=200),
        ),
        migrations.AlterField(
            model_name="correction",
            name="contenu",
            field=models.FileField(
                blank=True, null=True, upload_to="corrections_pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="exercice",
            name="contenu",
            field=models.FileField(blank=True, null=True, upload_to="exercices_pdfs/"),
        ),
        migrations.AlterField(
            model_name="lecon",
            name="contenu",
            field=models.FileField(blank=True, null=True, upload_to="lecons_pdfs/"),
        ),
    ]
